services:
  postgres:
    image: postgres:17
    container_name: kursova_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kursova
      TZ: Europe/Kyiv
    ports:
      - "5432:5432"